name: msf
channels:
  - conda-forge
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - anyio=3.6.2
  - aom=3.5.0
  - appdirs=1.4.4
  - audioread=3.0.0
  - backports=1.0
  - black=22.10.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - contourpy=1.0.6
  - cycler=0.11.0
  - decorator=5.1.1
  - expat=2.5.0
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - h11=0.14.0
  - icu=70.1
  - idna=3.4
  - importlib_metadata=5.1.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libffi=3.4.2
  - libflac=1.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - librosa=0.9.2
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - llvmlite=0.39.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - more-itertools=9.0.0
  - mpg123=1.30.2
  - music21=8.1.0
  - mypy_extensions=0.4.3
  - nbconvert=7.2.5
  - nbconvert-pandoc=7.2.5
  - ncurses=6.3
  - nettle=3.8.1
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - p11-kit=0.24.1
  - packaging=21.3
  - pandoc=2.19.2
  - pip=22.3.1
  - platformdirs=2.5.2
  - pooch=1.6.0
  - prompt_toolkit=3.0.33
  - pthread-stubs=0.4
  - pycparser=2.21
  - pydantic=1.10.2
  - pyparsing=3.0.9
  - pysoundfile=0.11.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.1.2
  - requests=2.28.1
  - resampy=0.4.2
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - setuptools=65.5.1
  - six=1.16.0
  - sniffio=1.3.0
  - svt-av1=1.3.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - webcolors=1.12
  - wheel=0.38.4
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zstd=1.5.2
  - pip:
    - async-timeout==4.0.2
    - chardet==5.0.0
    - deprecated==1.2.13
    - fastapi==0.85.2
    - jsonpickle==2.2.0
    - numba==0.56.3
    - numpy==1.23.4
    - pathspec==0.10.1
    - pillow==9.3.0
    - pyaudio==0.2.12
    - pyclean==2.2.0
    - redis==4.3.4
    - setuptools-scm==7.0.5
    - starlette==0.20.4
    - urllib3==1.26.12
    - uvicorn==0.19.0
    - wrapt==1.14.1
